export const WALLET_CREATE = "WALLET_CREATE"; // 创建钱包
export const WALLET_UPDATE = "WALLET_UPDATE"; // 更新钱包
export const WALLET_CREATE_ACCOUNT = "WALLET_CREATE_ACCOUNT"; // 创建账户
export const WALLET_DELETE_ACCOUNT = "WALLET_DELETE_ACCOUNT"; // 删除账户

export const UPDATE_PASSWOED = "UPDATE_PASSWOED"; // 更新密码
export const WALLET_UPDATE_WITHOUT_SAVE = "WALLET_UPDATE_WITHOUT_SAVE"; // 更新钱包并保存到本地