
// Objective-C API for talking to the following Go packages
//
//	account
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Account_FRAMEWORK_H__
#define __Account_FRAMEWORK_H__

#include "Account.objc.h"
#include "Universe.objc.h"

#endif
