// Objective-C API for talking to account Go package.
//   gobind -lang=objc account
//
// File is generated by gobind. Do not edit.

#ifndef __Account_H__
#define __Account_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class AccountChild;
@class AccountMaster;
@class AccountSign;

@interface AccountChild : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init:(NSData* _Nullable)key;
- (NSString* _Nonnull)addressHex;
- (NSString* _Nonnull)privateKeyHex;
- (NSString* _Nonnull)publicKeyHex;
- (NSString* _Nonnull)sign:(NSString* _Nullable)dataHex value:(int64_t)value nonce:(int64_t)nonce targetAddr:(NSString* _Nullable)targetAddr p4:(long)p4 gasLimit:(int64_t)gasLimit gasPrice:(int64_t)gasPrice extraDataHex:(NSString* _Nullable)extraDataHex;
@end

@interface AccountMaster : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init:(NSString* _Nullable)mnemonic;
- (AccountChild* _Nullable)getChild:(long)index error:(NSError* _Nullable* _Nullable)error;
- (AccountChild* _Nullable)tryGetChild:(long)index;
@end

/**
 * Sign Data struct
 */
@interface AccountSign : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
- (NSData* _Nullable)bytes;
@end

FOUNDATION_EXPORT const int64_t AccountSignLength;

@interface Account : NSObject
// skipped variable DefaultRootDerivationPath with unsupported type: []uint32

@end

FOUNDATION_EXPORT NSString* _Nonnull AccountGenMnemonic(void);

FOUNDATION_EXPORT NSString* _Nonnull AccountGetChild(NSString* _Nullable mnemonic, long index);

FOUNDATION_EXPORT AccountChild* _Nullable AccountNewChild(NSData* _Nullable key);

FOUNDATION_EXPORT AccountMaster* _Nullable AccountNewMaster(NSString* _Nullable mnemonic);

FOUNDATION_EXPORT NSString* _Nonnull AccountSignTx(NSString* _Nullable sk, NSString* _Nullable dataHex, int64_t value, int64_t nonce, NSString* _Nullable targetAddr, long p5, int64_t gasLimit, int64_t gasPrice, NSString* _Nullable extraDataHex);

FOUNDATION_EXPORT NSString* _Nonnull AccountSk2Addr(NSString* _Nullable sk);

FOUNDATION_EXPORT NSString* _Nonnull AccountSk2Pk(NSString* _Nullable sk);

#endif
